name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
  - cron: '0 0,8,16 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v4
    - name: Make script to fetch /overview-search executable
      run: chmod +x ./curl-overview-search-min.sh
    - name: Fetch /overview-search
      run: ./curl-overview-search-min.sh
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push